Correctly return Notimplemented for operations between operators (#1599)
This makes it such that in #1598 he would get the error

```
TypeError: unsupported operand type(s) for *: 'FermionOperator2nd' and 'LocalOperator'
```
instead of the unreadable
```
TypeError: unsupported operand type(s) for *: 'type' and 'type'
```